### ISSUE TITLE
Backend do Módulo admin

### ISSUE THREAD

**Issue by diogoatc** [diogoatc/projcomunicacao#8]
Criação de função para cadastrar disciplinas

- [ ] Input text para inserir o nome da matéria
- [ ] Select para escolher a quantidade de créditos (A se verificar as quantidades de créditos da disciplina disponíveis
- [ ] Botão para cadastrar a matéria (Botão simples, pois vai ser alterado no front
- [ ] Verificação se a disciplina já foi cadastrada
- [ ] Insert no BD da disciplina

_Inicialmente criar nova página para essa função_
